spring.application.name=task-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/tareas
spring.datasource.username=app
spring.datasource.password=secret_local_dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized